FROM arm64v8/node:alpine

# create app directory
WORKDIR /app

# install simple monitor script for use during development of a node.js app
#RUN npm install -g nodemon

# install app dependencies
# a wildcard is used to ensure both package.json and package-lock.json are copied where available (npm@5+)
ADD package*.json ./

#RUN npm config set registry http://registry.npmjs.org

RUN npm install && npm ls
# if buidling code or production:
#RUN npm install --only=production && npm ls

#RUN mv /app/node_modules /node_modules

#ADD . /app

# bundle app source
COPY . .

#ENV PORT 80
EXPOSE 8080

#ENV NODE_ENV=production

#CMD ["node", "index.js"]
CMD [ "npm", "start" ]

USER node
