version: '2'
services:
    traefik:
        image: traefik:alpine
        container_name: traefik
        command: --api --docker --docker.domain=alarmmonitor.local # Enables the web UI and tells Træfik to listen to docker
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080" # The Web UI (enabled by --api)
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
            - ./traefik/traefik.toml:/traefik.toml
        networks:
            - proxy
        labels:
            - "traefik.frontend.rule=Host:traefik.alarmmonitor.local"
            - "traefik.port=8080" 
        restart: unless-stopped
        
        
    ###############################################
    # Content from alarmDisplayApp/Dockerfile.cross
    ###############################################
    alarmdisplay-app:
        image: t08094a/alarmdisplay-app:latest
        container_name: alarmdisplay-app
        # hostname: app
        # domainname: alarmdisplay.local
        ports:
            - "9001:80"
        env_file: .env
        # networks:
        #     - network_frontend
        restart: unless-stopped
        depends_on:
            - datacenter-app

    ################################################
    # Content from dataCenter/src/app/docker/app.yml
    ################################################
    datacenter-app:
        image: t08094a/alarmdisplay-datacenter:latest
        container_name: datacenter-app
        # hostname: datacenter
        # domainname: alarmdisplay.local
        env_file: .env
        environment:
            - START_SLEEP=10 # gives time for the database to boot before the application
            #- MONGO_URL=mongodb://datacenter-mongodb/alarmdisplay-datacenter
        ports:
            - "9002:3000"
        # networks:
        #     - network_backend
        #     - network_frontend
        restart: unless-stopped
        depends_on:
            - datacenter-mongodb
                
    datacenter-mongodb:
        extends:
            file: dataCenter/docker/mongo.yml
            service: datacenter-mongodb
        container_name: datacenter-mongodb
        volumes:
            - datacenter-mongodb_volume:/data/db/
        # networks:
        #     - network_backend
        restart: unless-stopped
    
    # datacenter-mongodb-express:
    #     extends:
    #         file: dataCenter/docker/mongoexpress.yml
    #         service: datacenter-mongodb-express
    #     container_name: datacenter-mongodb-express
    #     hostname: alarmdisplay-mongodb-express
    #     domainname: alarmdisplay-mongodb-express.local
    #     # environment:
    #     ports:
    #         - "9003:8081"
    #     networks:
    #         - network_backend
    #     restart: unless-stopped
    #     depends_on:
    #         - datacenter-mongodb
    
                
volumes:
    datacenter-mongodb_volume:

networks:
    proxy:
        # external: true
    network_backend:
    network_frontend:
