# Traefik Global Configuration
debug = false
checkNewVersion = true
logLevel = "ERROR"

# Define the EntryPoint for HTTP and HTTPS
defaultEntryPoints = ["https","http"]

# Enable Traefik Dashboard on port 8080
# with basic authentication method -> http://www.htaccesstools.com/htpasswd-generator/
[web]
address = ":8080"
[web.auth.basic]
users = ["odin:$apr1$BUf5e./m$P4/1BYjtVykieuJlR9jUJ1"]

# Define the HTTP port 80 and
# HTTPS port 443 EntryPoint
# Enable automatically redirect HTTP to HTTPS
[entryPoints]
    [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
            entryPoint = "https"
    [entryPoints.https]
        address = ":443"
        # [entryPoints.https.tls]

# Enable retry sending a request if the network error
[retry]

# Define Docker Backend Configuration
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.alarmmonitor.local"
watch = true
exposedbydefault = false

# Letsencrypt Registration
# Define the Letsencrypt ACME HTTP challenge
# storage: File or key used for certificates storage.
# [acme]
# email = "jochen.faehnlein@gmail.com"
# storage = "acme.json"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
# entryPoint = "https"
# OnHostRule = true
#     [acme.httpChallenge]
#     entryPoint = "http"

# [[acme.domains]]
#   main = "alarmmonitor.local"
#   sans = ["portainer.alarmmonitor.local", "traefik.alarmmonitor.local", "alarmdisplay-app.alarmdisplay.alarmmonitor.local"]