#!/bin/bash

action=$1

if [ "$action" == "start" ] 
    then
        echo "Starte docker compose application ..."
        docker-compose -f src/main/docker/app.yml up -d
elif [ "$action" == "stop" ]
    then
        echo "Stoppe docker compose application ..."
        docker-compose -f src/main/docker/app.yml down 
else
    echo "usage: $0 start|stop"
fi
